### ISSUE TITLE
Server crashing randomly after latest Updates

### ISSUE THREAD

**Issue by tchncs** [cornernote/minetest-craft_guide#10]
This Issue is interesting - the first half Hour all was fine, than, the Server crashes and restarting.
First after using the Guide, than, without anyone touched it.
Here is the Output:
http://hastebin.com/ikudoxabib.lua

**Comment by Miner59** [comment]
Ok, I hope it works now again after I added a small check.
Sorry for the server crashes.

**Comment by tchncs** [comment]
Thank you very much for your fast response!
Seems stable now - i hope i answer not to fast ;)
