### ISSUE TITLE
digging 10 dirt does nothing

### ISSUE THREAD

**Issue by stormchaser3000** [cornernote/minetest-craft_guide#13]
<img src="http://u.cubeupload.com/stormchaser3000/screenshot2015072818.png">

EDIT: ima test this and see if i can get digging dirt to work

EDIT: THIS issue appears to be placing 10 dirt does nothing not digging dirt does nothing

**Comment by cornernote** [comment]
thanks, 

i must have put a bug in it last night.  should be fixed now

**Comment by cornernote** [comment]
nope, now nothing works... leave it with me and i'll sort it out

**Comment by cornernote** [comment]
also, this is craft_guide project, I assume you ment to post it as an issue here:
https://github.com/cornernote/minetest-skyblock/issues

**Comment by stormchaser3000** [comment]
oh oops yes i did mean to upload that to minetest-skyblock XD i will transfer the first post
